development:
  adapter: postgresql
  encoding: unicode
  database: hacksession_dev
  pool: 5
  username: hacksession
  password: hacksession

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost
  port: 5433


test:
  adapter: postgresql
  encoding: unicode
  database: hacksession_test
  pool: 5
  username: hacksession
  password: hacksession
  host: localhost
  port: 5433

staging:
  adapter: postgresql
  encoding: unicode
  database: hacksession_staging
  pool: 5
  username: postgres
  password: postgres
  #host: localhost
  #port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: hacksession
  pool: 5
  username: postgres
  password: postgres
  #host: localhost
  #port: 5432
